/* Optional DOM-only regression; npm install jsdom separately. No visual/layout proof. */
'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'..');
const dom=new JSDOM(fs.readFileSync(path.join(root,'static/index.html'),'utf8'),{url:'http://127.0.0.1:8818/',runScripts:'outside-only',pretendToBeVisual:true});
const {window}=dom;
window.structuredClone=structuredClone;
window.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
window.HTMLDialogElement.prototype.close=function(){this.open=false;};
const source=fs.readFileSync(path.join(root,'static/app.js'),'utf8').replace("document.addEventListener('DOMContentLoaded',initialize,{once:true});",'');
window.eval(source+`\nwindow.testUI={ui,renderRun,renderState,selectAgent,showView,setBriefOpen,renderSettings,renderProfileChoices,initialize};`);
const {ui,renderState,selectAgent,showView,setBriefOpen,renderSettings,renderProfileChoices}=window.testUI;
const $=id=>window.document.getElementById(id);
ui.config=JSON.parse(fs.readFileSync(path.join(root,'docs/interface.json'),'utf8')).config;
renderSettings();renderProfileChoices();renderState();
assert.equal($('workEmpty').hidden,false);
assert.equal(window.document.querySelector('.conversation-panel').hidden,true);
setBriefOpen(true);setBriefOpen(true);$('taskInput').value='下書き';setBriefOpen(false);setBriefOpen(true);assert.equal($('taskInput').value,'下書き');setBriefOpen(false);
showView('settings');showView('settings');showView('work');assert.equal($('settingsDialog').open,false);
ui.state.runs=[{id:'r',status:'working',task:'チームで確認',max_workers:16}];
ui.state.agents=[{id:'p',run_id:'r',name:'PM',role:'pm',profile_id:'local',status:'waiting',question:'確認してください',logs:[{id:1,kind:'assistant',text:'安全な文字列 <img src=x onerror=alert(1)>',thinking:'思考'}]},...Array.from({length:16},(_,i)=>({id:'w'+i,run_id:'r',parent_id:'p',name:'担当者'+i,role:'worker',profile_id:'local',status:'working',logs:[]}))];
ui.state.events=[{id:1,run_id:'r',kind:'mail',from:'担当者0',to:'PM',text:'<img src=x onerror=alert(1)>'}];
renderState();
assert.equal($('workEmpty').hidden,true);
assert.equal($('agentCards').children.length,17);
assert.equal($('agentTabs').children.length,17);
assert.equal($('teamMap').querySelectorAll('button').length,17);
assert.equal($('teamMap').querySelectorAll('.map-children').length,1);
assert.equal($('needsYou').textContent,'回答待ち 1');
assert.equal(window.document.querySelectorAll('img').length,0);
assert.equal($('conversationLog').querySelector('details').open,false);
const card=$('agentCards').children[0];card.focus();renderState();assert.equal(window.document.activeElement,card);
ui.state.agents[0].status='working';renderState();assert.equal(window.document.activeElement.dataset.focusKey,'agent:p');ui.state.agents[0].status='waiting';
$('messageInput').value='PMの下書き';selectAgent('w0');$('messageInput').value='担当の下書き';selectAgent('p');assert.equal($('messageInput').value,'PMの下書き');
ui.needsOnly=true;renderState();assert.equal($('agentCards').children.length,1);
ui.needsOnly=false;ui.state.agents[16].assignment='独自の割当';$('agentSearch').value='独自の割当';renderState();assert.equal($('agentCards').children.length,1);
$('agentSearch').value='';renderState();
assert.equal($('saveSettings').disabled,true);
ui.state.agents[1].role='pm';renderState();assert.equal($('agentCards').children[1].querySelector('.agent-avatar').textContent,'W1');
ui.state.agents[0].message_eligibility={allowed:false,reason:'settings_changed',message:'設定が変更されています。'};renderState();assert.equal($('sendMessage').disabled,true);assert.equal($('messageEligibility').textContent,'設定が変更されています。');
ui.state.runs[0].status='stopped';renderState();assert.equal($('saveSettings').disabled,false);assert.equal($('messageInput').disabled,true);
ui.state.agents[0].parent_id='w0';renderState();assert.equal($('teamMap').querySelectorAll('button').length,17);
console.log('DOM smoke passed: empty/active views, dialogs, 17-agent tree and cyclic-data guard, roster search/filter, escaped content, draft preservation, poll-stable focus, settings lock, stop. Dialog APIs shimmed; no browser layout/visual claim.');
dom.window.close();
